title: Alex Ashley
email: alexashley15@gmail.com
description: ""
baseurl: ""
url: "https://alexashley.dev"
github_username:  alexashley
linkedin_username: alex-h-ashley
rss: rss
theme: minima
plugins:
  - jekyll-feed

exclude:
  - .idea/
