title: Alex Ashley
email: alexashley15@gmail.com
description: >-
  I'm a software engineer passionate about APIs, authentication systems, and application security. I have experience with JavaScript, Kotlin, and C#.
baseurl: ""
url: "https://alexashley.dev"
github_username:  alexashley
linkedin_username: alex-h-ashley

theme: minima
plugins:
  - jekyll-feed

exclude:
  - .idea/
